#!/bin/sh

set -eu

if env | grep '^PYTHONPATH=' > /dev/null
then
    PYTHONPATH="$PYTHONPATH:."
else
    PYTHONPATH="."
fi

yarn --env "PYTHONPATH=$PYTHONPATH" \
     --shell python2 --shell-arg '' manual.yarn "$@"
