#!/usr/bin/python
#
# Copyright (C) 2014  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import Crypto.Cipher.ARC4

import cliapp


class MakeJunk(cliapp.Application):

    def add_settings(self):
        self.settings.bytesize(
            ['bytes'],
            'produce SIZE bytes of output',
            metavar='SIZE')

    def process_args(self, args):
        key = 'seed'
        data = 'x' * (10 * 1024**2)
        arc4 = Crypto.Cipher.ARC4.new(key)

        remaining = self.settings['bytes']
        while remaining > 0:
            junk = arc4.encrypt(data)[:remaining]
            self.output.write(junk)
            remaining -= len(junk)


MakeJunk().run()
